services:
  web:
    build:
      context: .
      target: production
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=True
      - NODE_ENV=development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
      - typescript-dev

  typescript-dev:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development

  css-dev:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm install && npm run css:dev"
    environment:
      - NODE_ENV=development

volumes:
  node_modules: 