# Generated by Django 5.2.4 on 2025-07-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing_lists', '0011_remove_packinglist_custom_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='price',
            name='confidence',
            field=models.CharField(choices=[('high', 'High - Verified receipt/website'), ('medium', 'Medium - Personal observation'), ('low', 'Low - Estimated/heard from others')], default='medium', help_text='Confidence level in price accuracy', max_length=10),
        ),
        migrations.AddField(
            model_name='price',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['item', 'store'], name='packing_lis_item_id_9a1157_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['item', 'created_at'], name='packing_lis_item_id_77ea18_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['confidence'], name='packing_lis_confide_43d4b5_idx'),
        ),
    ]
