# Generated by Django 5.2.4 on 2025-07-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing_lists', '0012_add_price_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='flagged_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times flagged as suspicious'),
        ),
        migrations.AddField(
            model_name='price',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of submitter for abuse prevention', null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified by trusted source or repeat contributor'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['ip_address', 'created_at'], name='packing_lis_ip_addr_2632de_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['flagged_count'], name='packing_lis_flagged_5adb93_idx'),
        ),
    ]
