# Generated by Django 5.2.4 on 2025-08-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing_lists', '0014_add_item_image_field'),
    ]

    operations = [
        # Add basic indexes compatible with SQLite for initial deployment
        # PostgreSQL-specific indexes will be added later via manual migration
        
        # Store location indexes
        migrations.RunSQL([
            "CREATE INDEX idx_store_location ON packing_lists_store(latitude, longitude);",
        ], reverse_sql=[
            "DROP INDEX IF EXISTS idx_store_location;",
        ]),
        
        # PackingListItem indexes
        migrations.RunSQL([
            "CREATE INDEX idx_packinglistitem_list_section ON packing_lists_packinglistitem(packing_list_id, section);",
            "CREATE INDEX idx_packinglistitem_list_required ON packing_lists_packinglistitem(packing_list_id, required);",
        ], reverse_sql=[
            "DROP INDEX IF EXISTS idx_packinglistitem_list_section;",
            "DROP INDEX IF EXISTS idx_packinglistitem_list_required;",
        ]),
        
        # Basic price indexes
        migrations.RunSQL([
            "CREATE INDEX idx_price_item_confidence ON packing_lists_price(item_id, confidence);",
        ], reverse_sql=[
            "DROP INDEX IF EXISTS idx_price_item_confidence;",
        ]),
        
        # Vote indexes
        migrations.RunSQL([
            "CREATE INDEX idx_vote_price_correct ON packing_lists_vote(price_id, is_correct_price);",
        ], reverse_sql=[
            "DROP INDEX IF EXISTS idx_vote_price_correct;",
        ]),
    ]
