# Generated by Django 5.2.4 on 2025-08-12 22:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing_lists', '0014_add_item_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Allow this list to be shared publicly'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='share_slug',
            field=models.SlugField(blank=True, help_text='Unique URL slug for sharing', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this list has been viewed'),
        ),
    ]
